name: Deploy to InfinityFree

on:
  push:
    branches:
      - main   # Change if your repo uses 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./   # The folder from your repo to upload
          server-dir: /htdocs/   # InfinityFree’s public directory
